<?php
declare(strict_types=1);

return [
    'settings' => [
        ['setting_key' => 'site_name', 'setting_value' => 'Bisped'],
        ['setting_key' => 'site_tagline', 'setting_value' => 'Informatica, telefonia e assistenza tecnica'],
        ['setting_key' => 'contact_email', 'setting_value' => 'info@bisped.net'],
        ['setting_key' => 'business_telegram', 'setting_value' => 'mailto:info@bisped.net'],
        ['setting_key' => 'hero_title_home', 'setting_value' => 'Tecnologia concreta per casa, lavoro e impresa.'],
        ['setting_key' => 'hero_subtitle_home', 'setting_value' => 'Bisped porta online negozio, laboratorio, catalogo prodotti, preventivi e assistenza: competenza tecnica vera e persone competenti al tuo fianco, per privati e aziende.'],
        ['setting_key' => 'hero_image_home', 'setting_value' => '/media/bisped/fronte_negozio_bisped.png'],
        ['setting_key' => 'hero_badge_home', 'setting_value' => 'Negozio, laboratorio e soluzioni digitali per casa e impresa a Piombino.'],
        ['setting_key' => 'site_logo', 'setting_value' => '/media/bisped/bisped_logo.png'],
        ['setting_key' => 'favicon_path', 'setting_value' => '/media/bisped/cropped-logobisped.png'],
        ['setting_key' => 'og_image', 'setting_value' => '/media/bisped/fronte_negozio_bisped.png'],
        ['setting_key' => 'seo_share_image', 'setting_value' => '/media/bisped/fronte_negozio_bisped.png'],
        ['setting_key' => 'seo_meta_title', 'setting_value' => 'Bisped | Informatica, telefonia e assistenza tecnica'],
        ['setting_key' => 'seo_meta_description', 'setting_value' => 'Bisped offre vendita assistita, riparazioni, supporto IT, telefonia, gaming hardware, preventivi e soluzioni per aziende.'],
        ['setting_key' => 'seo_social_title', 'setting_value' => 'Bisped - Tecnologia concreta'],
        ['setting_key' => 'seo_social_description', 'setting_value' => 'Bisped Piombino: prodotti tech, riparazioni, connettività, energia e soluzioni digitali su misura per privati e aziende.'],
        ['setting_key' => 'seo_twitter_description', 'setting_value' => 'Bisped | Informatica, telefonia, assistenza tecnica e catalogo prodotti.'],
        ['setting_key' => 'seo_telegram_description', 'setting_value' => 'Bisped | Vendita e assistenza IT con richiesta preventivo online.'],
        ['setting_key' => 'seo_discord_description', 'setting_value' => 'Bisped | Soluzioni IT, telefonia e supporto tecnico.'],
        ['setting_key' => 'storefront_image', 'setting_value' => '/media/bisped/fronte_negozio_bisped.png'],
    ],
    'products' => [
        [
            'name' => 'SHARKOON CUFFIA STEREO USB RUSH ER40 , MULTI-COLORED-ILLUMINATION, 3D RGB',
            'slug' => 'sharkoon-cuffia-stereo-usb-rush-er40-multi-colored-illumination-3d-rgb',
            'description' => 'Prodotto CUFFIE E MICROFONI importato dal WooCommerce Bisped. Prezzo indicativo: EUR 45.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SHARKOON CUFFIA STEREO USB RUSH ER40 , MULTI-COLORED-ILLUMINATION, 3D RGB',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto CUFFIE E MICROFONI importato dal WooCommerce Bisped. Prezzo indicativo: EUR 45.</p><ul><li>Categoria: CUFFIE E MICROFONI</li><li>Prezzo WooCommerce: EUR 45</li><li>SKU/IMEI: SHARKOON ER40</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SHARKOON CUFFIE SKILLER SGH2',
            'slug' => 'sharkoon-cuffie-skiller-sgh2',
            'description' => 'Prodotto CUFFIE E MICROFONI importato dal WooCommerce Bisped. Prezzo indicativo: EUR 19.99.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SHARKOON CUFFIE SKILLER SGH2',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto CUFFIE E MICROFONI importato dal WooCommerce Bisped. Prezzo indicativo: EUR 19.99.</p><ul><li>Categoria: CUFFIE E MICROFONI</li><li>Prezzo WooCommerce: EUR 19.99</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SHARKOON CUFFIE SKILLER SGH2 CON MICROFONO, USB, LUNGHEZZA CAVO 2,5M',
            'slug' => 'sharkoon-cuffie-skiller-sgh2-con-microfono-usb-lunghezza-cavo-25m',
            'description' => 'Prodotto CUFFIE E MICROFONI importato dal WooCommerce Bisped. Prezzo indicativo: EUR 29.9.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SHARKOON CUFFIE SKILLER SGH2 CON MICROFONO, USB, LUNGHEZZA CAVO 2,5M',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto CUFFIE E MICROFONI importato dal WooCommerce Bisped. Prezzo indicativo: EUR 29.9.</p><ul><li>Categoria: CUFFIE E MICROFONI</li><li>Prezzo WooCommerce: EUR 29.9</li><li>SKU/IMEI: SKILLER SGH2</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SHARKOON TASTIERA GAMING A MEMBRANA SKILLER SGK4 RGB, LAYOUT ITA',
            'slug' => 'sharkoon-tastiera-gaming-a-membrana-skiller-sgk4-rgb-layout-ita',
            'description' => 'Prodotto TASTIERE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 31.48.',
            'icon_key' => 'cube',
            'hero_title' => 'SHARKOON TASTIERA GAMING A MEMBRANA SKILLER SGK4 RGB, LAYOUT ITA',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto TASTIERE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 31.48.</p><ul><li>Categoria: TASTIERE</li><li>Prezzo WooCommerce: EUR 31.48</li><li>SKU/IMEI: SKILLER SGK4 IT</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SHARKOON TASTIERA GAMING MECCANICA SKILLER MECH SGK30, SWITCH RED, LAYOUT ITA, RGB PERSONALIZZABILE',
            'slug' => 'sharkoon-tastiera-gaming-meccanica-skiller-mech-sgk30-switch-red-layout-ita-rgb-personalizzabile',
            'description' => 'Prodotto TASTIERE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 59.9.',
            'icon_key' => 'cube',
            'hero_title' => 'SHARKOON TASTIERA GAMING MECCANICA SKILLER MECH SGK30, SWITCH RED, LAYOUT ITA, RGB PERSONALIZZABILE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto TASTIERE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 59.9.</p><ul><li>Categoria: TASTIERE</li><li>Prezzo WooCommerce: EUR 59.9</li><li>SKU/IMEI: SKILLER MECH SGK30 R</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'YASHI NB SUZUKA J4125',
            'slug' => 'yashi-nb-suzuka-j4125',
            'description' => 'YASHI NB SUZUKA J4125 8GB 240GB + 64GB SSD 14,1 Prezzo indicativo: EUR 349.',
            'icon_key' => 'chip',
            'hero_title' => 'YASHI NB SUZUKA J4125',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>YASHI NB SUZUKA J4125 8GB 240GB + 64GB SSD 14,1 Prezzo indicativo: EUR 349.</p><ul><li>Categoria: NOTEBOOK</li><li>Prezzo WooCommerce: EUR 349</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'MSI MONITOR 27 LED IPS',
            'slug' => 'msi-monitor-27-led-ips',
            'description' => 'MSI MONITOR 27 LED IPS 16.9 FHD 5MS 250 CDM, VGA/HDMI, PIVOT , MULTIMEDIALE Prezzo indicativo: EUR 239.',
            'icon_key' => 'cube',
            'hero_title' => 'MSI MONITOR 27 LED IPS',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>MSI MONITOR 27 LED IPS 16.9 FHD 5MS 250 CDM, VGA/HDMI, PIVOT , MULTIMEDIALE Prezzo indicativo: EUR 239.</p><ul><li>Categoria: Monitor</li><li>Prezzo WooCommerce: EUR 239</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'Huawei Y6P (2020) Dual Sim 3GB RAM 64GB – Black Nero',
            'slug' => 'huawei-y6p-2020-dual-sim-3gb-ram-64gb-black-nero',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 119.99.',
            'icon_key' => 'device-phone',
            'hero_title' => 'Huawei Y6P (2020) Dual Sim 3GB RAM 64GB – Black Nero',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 119.99.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 119.99</li><li>SKU/IMEI: 6972453162458</li><li>Stato importato: Da verificare</li></ul>',
        ],
        [
            'name' => 'LG K30 2019 16GB 2GB RAM Dual Sim Black Italia',
            'slug' => 'lg-k30-2019-16gb-2gb-ram-dual-sim-black-italia',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 110.89.',
            'icon_key' => 'device-phone',
            'hero_title' => 'LG K30 2019 16GB 2GB RAM Dual Sim Black Italia',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 110.89.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 110.89</li><li>SKU/IMEI: 8806087040265</li><li>Stato importato: Da verificare</li></ul>',
        ],
        [
            'name' => 'Oppo A53 S 128GB /4GB ELECTRIC BLACK',
            'slug' => 'oppo-a53-s-128gb-4gb-electric-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 199.',
            'icon_key' => 'device-phone',
            'hero_title' => 'Oppo A53 S 128GB /4GB ELECTRIC BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 199.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 199</li><li>SKU/IMEI: 6944284670839</li><li>Stato importato: Da verificare</li></ul>',
        ],
        [
            'name' => 'Oppo A53s 128GB /4GB ELECTRIC BLACK',
            'slug' => 'oppo-a53s-128gb-4gb-electric-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 199.99.',
            'icon_key' => 'device-phone',
            'hero_title' => 'Oppo A53s 128GB /4GB ELECTRIC BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 199.99.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 199.99</li><li>SKU/IMEI: 8032325308761</li><li>Stato importato: Da verificare</li></ul>',
        ],
        [
            'name' => 'Oppo A53s 128GB /4GB ELECTRIC BLUE',
            'slug' => 'oppo-a53s-128gb-4gb-electric-blue',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 199.',
            'icon_key' => 'device-phone',
            'hero_title' => 'Oppo A53s 128GB /4GB ELECTRIC BLUE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 199.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 199</li><li>SKU/IMEI: 6944284670853</li><li>Stato importato: Da verificare</li></ul>',
        ],
        [
            'name' => 'OPPO A53S 4G 128GB BLUE',
            'slug' => 'oppo-a53s-4g-128gb-blue',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A53S 4G 128GB BLUE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 209</li><li>SKU/IMEI: 860283053512217</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A53S 4G 128GB BLUE',
            'slug' => 'oppo-a53s-4g-128gb-blue-2',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A53S 4G 128GB BLUE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 209</li><li>SKU/IMEI: 860283053511870</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A53S 4G 128GB BLUE',
            'slug' => 'oppo-a53s-4g-128gb-blue-3',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A53S 4G 128GB BLUE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 209</li><li>SKU/IMEI: 860283053511938</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A53S 4G 128GB BLUE',
            'slug' => 'oppo-a53s-4g-128gb-blue-4',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A53S 4G 128GB BLUE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 209</li><li>SKU/IMEI: 861395053871291</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A53S 4G 128GB BLUE',
            'slug' => 'oppo-a53s-4g-128gb-blue-5',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A53S 4G 128GB BLUE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 209</li><li>SKU/IMEI: 860283053511979</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A53S 4G 128GB BLUE',
            'slug' => 'oppo-a53s-4g-128gb-blue-6',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A53S 4G 128GB BLUE',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 209</li><li>SKU/IMEI: 861395053872299</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'Oppo A54 5g 4GB/64GB',
            'slug' => 'oppo-a54-5g-4gb-64gb',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 284.3.',
            'icon_key' => 'device-phone',
            'hero_title' => 'Oppo A54 5g 4GB/64GB',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 284.3.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 284.3</li><li>SKU/IMEI: 6944284684256</li><li>Stato importato: Da verificare</li></ul>',
        ],
        [
            'name' => 'OPPO A54S 4G 128GB BLACK',
            'slug' => 'oppo-a54s-4g-128gb-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A54S 4G 128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 239</li><li>SKU/IMEI: 869156052894391</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A54S 4G 128GB BLACK',
            'slug' => 'oppo-a54s-4g-128gb-black-2',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A54S 4G 128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 239</li><li>SKU/IMEI: 869156052893971</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A54S 4G 128GB BLACK',
            'slug' => 'oppo-a54s-4g-128gb-black-3',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A54S 4G 128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 239</li><li>SKU/IMEI: 869156052894094</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A54S 4G 128GB BLACK',
            'slug' => 'oppo-a54s-4g-128gb-black-4',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A54S 4G 128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 239.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 239</li><li>SKU/IMEI: 869156056176597</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO A94 5G 128GB BLACK',
            'slug' => 'oppo-a94-5g-128gb-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 379.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO A94 5G 128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 379.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 379</li><li>SKU/IMEI: 867620062063414</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO FIND X5 LITE 256GB BLACK',
            'slug' => 'oppo-find-x5-lite-256gb-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 499.99.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO FIND X5 LITE 256GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 499.99.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 499.99</li><li>SKU/IMEI: 862340055668351</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'OPPO FIND X5 LITE 5G BLACK',
            'slug' => 'oppo-find-x5-lite-5g-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 509.',
            'icon_key' => 'device-phone',
            'hero_title' => 'OPPO FIND X5 LITE 5G BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 509.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 509</li><li>SKU/IMEI: 862340053176878</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'REALME C21 4G 64GB BLACK',
            'slug' => 'realme-c21-4g-64gb-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 149.',
            'icon_key' => 'device-phone',
            'hero_title' => 'REALME C21 4G 64GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 149.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 149</li><li>SKU/IMEI: 869683052987792</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'REALME C21 4G 64GB BLACK',
            'slug' => 'realme-c21-4g-64gb-black-2',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 149.',
            'icon_key' => 'device-phone',
            'hero_title' => 'REALME C21 4G 64GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 149.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 149</li><li>SKU/IMEI: 869683052987651</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SAMSUNG GALAXY',
            'slug' => 'samsung-galaxy',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.14.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SAMSUNG GALAXY',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 209.14.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 209.14</li><li>SKU/IMEI: 351044514153835</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'Samsung Galaxy A12 Dual Sim 4GB RAM 64GB - Black',
            'slug' => 'samsung-galaxy-a12-dual-sim-4gb-ram-64gb-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 189.',
            'icon_key' => 'device-phone',
            'hero_title' => 'Samsung Galaxy A12 Dual Sim 4GB RAM 64GB - Black',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 189.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 189</li><li>SKU/IMEI: 8806090828089</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SAMSUNG GALAXY A13 4G\\n128GB BLACK',
            'slug' => 'samsung-galaxy-a13-4g128gb-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 229.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SAMSUNG GALAXY A13 4G\\n128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 229.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 229</li><li>SKU/IMEI: 351044514199101</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SAMSUNG GALAXY A13 4G\\n128GB BLACK',
            'slug' => 'samsung-galaxy-a13-4g128gb-black-2',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 229.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SAMSUNG GALAXY A13 4G\\n128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 229.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 229</li><li>SKU/IMEI: 351044514153835</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SAMSUNG GALAXY A22 5G 64GB\\nGREY',
            'slug' => 'samsung-galaxy-a22-5g-64gbgrey',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 259.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SAMSUNG GALAXY A22 5G 64GB\\nGREY',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 259.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 259</li><li>SKU/IMEI: 352321546745427</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SAMSUNG GALAXY A22 5G 64GB\\nGREY',
            'slug' => 'samsung-galaxy-a22-5g-64gbgrey-2',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 259.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SAMSUNG GALAXY A22 5G 64GB\\nGREY',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 259.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 259</li><li>SKU/IMEI: 352321546745310</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SAMSUNG GALAXY A32 5G\\n128GB BLACK',
            'slug' => 'samsung-galaxy-a32-5g128gb-black',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 309.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SAMSUNG GALAXY A32 5G\\n128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 309.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 309</li><li>SKU/IMEI: 351946452651358</li><li>Stato importato: Disponibile</li></ul>',
        ],
        [
            'name' => 'SAMSUNG GALAXY A32 5G\\n128GB BLACK',
            'slug' => 'samsung-galaxy-a32-5g128gb-black-2',
            'description' => 'Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 309.',
            'icon_key' => 'device-phone',
            'hero_title' => 'SAMSUNG GALAXY A32 5G\\n128GB BLACK',
            'hero_subtitle' => 'Scheda importata dal catalogo WooCommerce Bisped. Richiedi conferma disponibilita e preventivo aggiornato.',
            'cta_text' => 'Richiedi disponibilita',
            'cta_link' => '/contatti',
            'content_html' => '<p>Prodotto SMARTPHONE importato dal WooCommerce Bisped. Prezzo indicativo: EUR 309.</p><ul><li>Categoria: SMARTPHONE</li><li>Prezzo WooCommerce: EUR 309</li><li>SKU/IMEI: 351946452656183</li><li>Stato importato: Disponibile</li></ul>',
        ]
    ],
    'product_features' => [
        'sharkoon-cuffia-stereo-usb-rush-er40-multi-colored-illumination-3d-rgb' => ['Categoria: CUFFIE E MICROFONI', 'Prezzo WooCommerce: EUR 45', 'Disponibile'],
        'sharkoon-cuffie-skiller-sgh2' => ['Categoria: CUFFIE E MICROFONI', 'Prezzo WooCommerce: EUR 19.99', 'Disponibile'],
        'sharkoon-cuffie-skiller-sgh2-con-microfono-usb-lunghezza-cavo-25m' => ['Categoria: CUFFIE E MICROFONI', 'Prezzo WooCommerce: EUR 29.9', 'Disponibile'],
        'sharkoon-tastiera-gaming-a-membrana-skiller-sgk4-rgb-layout-ita' => ['Categoria: TASTIERE', 'Prezzo WooCommerce: EUR 31.48', 'Disponibile'],
        'sharkoon-tastiera-gaming-meccanica-skiller-mech-sgk30-switch-red-layout-ita-rgb-personalizzabile' => ['Categoria: TASTIERE', 'Prezzo WooCommerce: EUR 59.9', 'Disponibile'],
        'yashi-nb-suzuka-j4125' => ['Categoria: NOTEBOOK', 'Prezzo WooCommerce: EUR 349', 'Disponibile'],
        'msi-monitor-27-led-ips' => ['Categoria: Monitor', 'Prezzo WooCommerce: EUR 239', 'Disponibile'],
        'huawei-y6p-2020-dual-sim-3gb-ram-64gb-black-nero' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 119.99', 'Da verificare'],
        'lg-k30-2019-16gb-2gb-ram-dual-sim-black-italia' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 110.89', 'Da verificare'],
        'oppo-a53-s-128gb-4gb-electric-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 199', 'Da verificare'],
        'oppo-a53s-128gb-4gb-electric-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 199.99', 'Da verificare'],
        'oppo-a53s-128gb-4gb-electric-blue' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 199', 'Da verificare'],
        'oppo-a53s-4g-128gb-blue' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 209', 'Disponibile'],
        'oppo-a53s-4g-128gb-blue-2' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 209', 'Disponibile'],
        'oppo-a53s-4g-128gb-blue-3' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 209', 'Disponibile'],
        'oppo-a53s-4g-128gb-blue-4' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 209', 'Disponibile'],
        'oppo-a53s-4g-128gb-blue-5' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 209', 'Disponibile'],
        'oppo-a53s-4g-128gb-blue-6' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 209', 'Disponibile'],
        'oppo-a54-5g-4gb-64gb' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 284.3', 'Da verificare'],
        'oppo-a54s-4g-128gb-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 239', 'Disponibile'],
        'oppo-a54s-4g-128gb-black-2' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 239', 'Disponibile'],
        'oppo-a54s-4g-128gb-black-3' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 239', 'Disponibile'],
        'oppo-a54s-4g-128gb-black-4' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 239', 'Disponibile'],
        'oppo-a94-5g-128gb-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 379', 'Disponibile'],
        'oppo-find-x5-lite-256gb-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 499.99', 'Disponibile'],
        'oppo-find-x5-lite-5g-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 509', 'Disponibile'],
        'realme-c21-4g-64gb-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 149', 'Disponibile'],
        'realme-c21-4g-64gb-black-2' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 149', 'Disponibile'],
        'samsung-galaxy' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 209.14', 'Disponibile'],
        'samsung-galaxy-a12-dual-sim-4gb-ram-64gb-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 189', 'Disponibile'],
        'samsung-galaxy-a13-4g128gb-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 229', 'Disponibile'],
        'samsung-galaxy-a13-4g128gb-black-2' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 229', 'Disponibile'],
        'samsung-galaxy-a22-5g-64gbgrey' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 259', 'Disponibile'],
        'samsung-galaxy-a22-5g-64gbgrey-2' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 259', 'Disponibile'],
        'samsung-galaxy-a32-5g128gb-black' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 309', 'Disponibile'],
        'samsung-galaxy-a32-5g128gb-black-2' => ['Categoria: SMARTPHONE', 'Prezzo WooCommerce: EUR 309', 'Disponibile'],
    ],
    'navigation_groups' => [
        ['menu_key' => 'header', 'group_key' => 'header_primary', 'title' => 'Header primary'],
        ['menu_key' => 'header', 'group_key' => 'header_more', 'title' => 'Header more'],
        ['menu_key' => 'header', 'group_key' => 'header_cta', 'title' => 'Header CTA'],
        ['menu_key' => 'footer', 'group_key' => 'footer_navigate', 'title' => 'Naviga'],
        ['menu_key' => 'footer', 'group_key' => 'footer_resources', 'title' => 'Risorse'],
        ['menu_key' => 'footer', 'group_key' => 'footer_community', 'title' => 'Canali'],
        ['menu_key' => 'footer', 'group_key' => 'footer_legal', 'title' => 'Legal'],
    ],
    'navigation_items' => [
        ['group_key' => 'header_primary', 'label' => 'Home', 'url' => '/'],
        ['group_key' => 'header_primary', 'label' => 'Azienda', 'url' => '/azienda'],
        ['group_key' => 'header_primary', 'label' => 'Servizi', 'url' => '/servizi'],
        ['group_key' => 'header_primary', 'label' => 'Catalogo', 'url' => '/products'],
        ['group_key' => 'header_primary', 'label' => 'Sostenibilita', 'url' => '/sostenibilita'],
        ['group_key' => 'header_more', 'label' => 'Blog', 'url' => '/blog'],
        ['group_key' => 'header_more', 'label' => 'FAQ', 'url' => '/faq'],
        ['group_key' => 'header_more', 'label' => 'Area riservata', 'url' => '/login'],
        ['group_key' => 'header_cta', 'label' => 'Contatti', 'url' => '/contatti'],
        ['group_key' => 'footer_navigate', 'label' => 'Azienda', 'url' => '/azienda'],
        ['group_key' => 'footer_navigate', 'label' => 'Servizi', 'url' => '/servizi'],
        ['group_key' => 'footer_navigate', 'label' => 'Catalogo', 'url' => '/products'],
        ['group_key' => 'footer_navigate', 'label' => 'Contatti', 'url' => '/contatti'],
        ['group_key' => 'footer_resources', 'label' => 'Sostenibilita', 'url' => '/sostenibilita'],
        ['group_key' => 'footer_resources', 'label' => 'Blog', 'url' => '/blog'],
        ['group_key' => 'footer_resources', 'label' => 'FAQ', 'url' => '/faq'],
        ['group_key' => 'footer_community', 'label' => 'Email', 'url' => 'mailto:info@bisped.net', 'is_external' => true],
        ['group_key' => 'footer_legal', 'label' => 'Privacy Policy', 'url' => '/legal'],
        ['group_key' => 'footer_legal', 'label' => 'Cookie Policy', 'url' => '/legal'],
    ],
    'faq_items' => [
        ['question' => 'Fate spedizioni o solo ritiro in negozio?', 'answer' => 'Entrambi. Spediamo in tutta Italia tramite corriere oppure puoi ritirare comodamente presso il nostro punto vendita a Piombino.'],
        ['question' => 'Quali metodi di pagamento accettate?', 'answer' => 'Bonifico bancario, carte di credito e debito, Satispay e pagamento direttamente presso il punto vendita.'],
        ['question' => 'Riparate anche dispositivi non acquistati da voi?', 'answer' => 'Sì. In laboratorio valutiamo PC, notebook, smartphone e periferiche di qualsiasi provenienza: facciamo prima una diagnosi, poi ti diciamo con chiarezza se conviene riparare o sostituire.'],
        ['question' => 'Il preventivo e la diagnosi sono a pagamento?', 'answer' => 'Il preventivo è gratuito e senza impegno. Ti spieghiamo il problema e i costi prima di procedere: decidi tu con tutte le informazioni in mano.'],
        ['question' => 'I prodotti hanno garanzia?', 'answer' => 'Sì. Tutti i prodotti sono coperti dalla garanzia legale di conformità di 24 mesi prevista per i consumatori, oltre alle eventuali garanzie del produttore.'],
        ['question' => 'Il catalogo prodotti è aggiornato?', 'answer' => 'Sì. Il catalogo è collegato al nostro distributore e aggiornato più volte al giorno con prezzi e disponibilità reali. Se cerchi un prodotto che non trovi, contattaci: possiamo ordinarlo.'],
        ['question' => 'Vi occupate anche di connettività ed energia?', 'answer' => 'Sì. Ti aiutiamo a confrontare e scegliere offerte di fibra, FWA e mobile per la connettività, e di luce e gas per l\'energia, con un approccio pratico e senza promesse generiche.'],
        ['question' => 'Lavorate anche con le aziende?', 'answer' => 'Sì. Seguiamo professionisti e imprese con fornitura, configurazione, reti, sicurezza, backup e assistenza continuativa, oltre a soluzioni digitali su misura.'],
        ['question' => 'Sviluppate davvero soluzioni di intelligenza artificiale?', 'answer' => 'Sì. Realizziamo applicativi su misura, chatbot e AI Agent per automatizzare attività, rispondere ai clienti e presidiare i canali online. Raccontaci l\'esigenza e troviamo la soluzione giusta.'],
    ],
    'blog_posts' => [
        [
            'slug' => 'benvenuti-da-bisped',
            'title' => 'Benvenuti da Bisped: tecnologia e persone competenti',
            'published_at' => '2026-05-26',
            'image_url' => '/media/bisped/fronte_negozio_bisped.png',
            'snippet' => 'Negozio, laboratorio e soluzioni digitali a Piombino: prodotti, riparazioni, connettività, energia e servizi su misura.',
            'content_html' => '<p>Da Bisped trovi prodotti tech selezionati, un laboratorio di riparazione, consulenza su connettività ed energia e soluzioni digitali su misura per privati e aziende. Persone competenti, non solo scaffali.</p>',
            'is_published' => 1,
        ],
    ],
    'legal_sections' => [
        [
            'title' => 'Privacy e cookie',
            'content_html' => '<p>Testi legali provvisori da sostituire con versioni definitive prima della pubblicazione.</p>',
        ],
    ],
];
